# Generated by Django 4.2.23 on 2025-07-09 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Plano')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Mensal')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('features', models.TextField(blank=True, help_text="Liste os recursos separados por vírgula (ex: '5 usuários, 10GB armazenamento')", verbose_name='Recursos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renovação Automática')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Último Pagamento')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Próxima Cobrança')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='Plano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (Placeholder para Empresa)')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'is_active'), name='inique_active_subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'plan', 'is_active')},
        ),
    ]
