# Generated by Django 4.2.23 on 2025-07-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscription_inique_active_subscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
