# Generated by Django 4.2.23 on 2025-07-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, help_text='Código EAN do produto', max_length=13, null=True, unique=True, verbose_name='EAN'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='un', help_text='Unidade de medida do produto', max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Categoria do produto', max_length=50, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço de custo do produto', max_digits=10, null=True, verbose_name='Custo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação do produto', null=True, verbose_name='Criação'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do produto', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca do produto', max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade mínima em estoque para alertas', verbose_name='Min. Estoque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Nome do produto', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade atual em estoque', verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço de venda do produto', max_digits=10, null=True, verbose_name='Venda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Código SKU do produto', max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data de atualização do produto', null=True, verbose_name='Atualização'),
        ),
    ]
