# Generated by Django 4.2.23 on 2025-07-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_ean_product_unit_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, help_text='Referência do produto', max_length=50, null=True, verbose_name='Referência'),
        ),
    ]
