# Generated by Django 4.2.23 on 2025-07-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local',
            field=models.CharField(blank=True, help_text='Localização do produto no estoque', max_length=100, null=True, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UN', 'Unidade(s)'), ('KG', 'Quilograma(s)'), ('LT', 'Litro(s)'), ('MT', 'Metro(s)'), ('DZ', 'Dúzia(s)')], default='UN', help_text='Unidade de medida do produto', max_length=2, verbose_name='Unidade de Medida'),
        ),
    ]
