# Generated by Django 4.2.23 on 2025-07-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_local_alter_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Categoria do produto', max_length=20, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='local',
            field=models.CharField(blank=True, help_text='Localização do produto no estoque', max_length=20, null=True, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca do produto', max_length=20, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, help_text='Referência do produto', max_length=20, null=True, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Código SKU do produto', max_length=20, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UN', 'Unidade(s)'), ('CX', 'Caixa(s)'), ('PCT', 'Pacote(s)'), ('PÇ', 'Peça(s)'), ('KG', 'Quilograma(s)'), ('LT', 'Litro(s)'), ('MT', 'Metro(s)'), ('DZ', 'Dúzia(s)')], default='UN', help_text='Unidade de medida do produto', max_length=3, verbose_name='Unidade de Medida'),
        ),
    ]
