# Generated by Django 4.2.23 on 2025-07-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_name_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Lente', 'Lente'), ('Óculos', 'Óculos'), ('Armação', 'Armação'), ('Acessórios', 'Acessório'), ('Equipamentos', 'Equipamento')], default='Óculos', help_text='Categoria do produto', max_length=20, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.marca'),
        ),
    ]
